const Testimonial=()=>{

    return(


<div class="elementor-element elementor-element-a33e6a6 e-con-full e-flex e-con e-parent"
                    data-id="a33e6a6" data-element_type="container">
                    <div class="elementor-element elementor-element-c0043ce elementor-widget elementor-widget-synckhomev1testimonial"
                        data-id="c0043ce" data-element_type="widget" data-widget_type="synckhomev1testimonial.default">
                        <div class="elementor-widget-container">


                        
                            <section class="testimonial-area">
                                <div class="custom-container">

                                    <div class="testimonial-slider-wrap">
                                        <div class="testimonial-slider swiper">

                                            <div class="swiper-wrapper">

                                                <div class="swiper-slide testimonial-item">
                                                    <div class="testimonial-item-body">
                                                        <img decoding="async" class="animation-slide-right bg-shape"
                                                            src="images/57hIxXHFpEOs.svg"/>

                                                        <span class="platform-name">
                                                            <img decoding="async" src="images/a50ozyj1Uik1.svg"/>
                                                        </span>
                                                        <h2>Platform helped me to increase my sales and revenue
                                                            generated by bluebase technologies</h2>
                                                        <p>One aspect that sets IT Services apart is their proactive
                                                            approach to security. In today's digital landscape,
                                                            protecting our sensitive data is of utmost importance.</p>
                                                        <div class="author-box d-flex align-items-center">
                                                            <img decoding="async" src="images/rH7L7GYu9n8r.jpg"/>
                                                            <div class="author-box-content">
                                                                <h5>Serana Belluci</h5>
                                                                <p>Product Designer</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="swiper-slide testimonial-item">
                                                    <div class="testimonial-item-body">
                                                        <img decoding="async" class="animation-slide-right bg-shape"
                                                            src="images/57hIxXHFpEOs.svg"/>

                                                        <span class="platform-name">
                                                            <img decoding="async" src="images/a50ozyj1Uik1.svg"/>
                                                        </span>
                                                        <h2>Bluebase give the best service and top customer
                                                            support. Really like to have more projects with you</h2>
                                                        <p>One aspect that sets IT Services apart is their proactive
                                                            approach to security. In today's digital landscape,
                                                            protecting our sensitive data is of utmost importance.</p>
                                                        <div class="author-box d-flex align-items-center">
                                                            <img decoding="async" src="images/8RbCdGfsvcTi.jpeg"/>
                                                            <div class="author-box-content">
                                                                <h5>Megan Clarke</h5>
                                                                <p>CEO, Sanlab</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="swiper-slide testimonial-item">
                                                    <div class="testimonial-item-body">
                                                        <img decoding="async" class="animation-slide-right bg-shape"
                                                            src="images/57hIxXHFpEOs.svg"/>

                                                        <span class="platform-name">
                                                            <img decoding="async" src="images/a50ozyj1Uik1.svg"/>
                                                        </span>
                                                        <h2>We’ve been using bluebase for a few years, It is very
                                                            simple and easy to approach team and management</h2>
                                                        <p>One aspect that sets IT Services apart is their proactive
                                                            approach to security. In today's digital landscape,
                                                            protecting our sensitive data is of utmost importance.</p>
                                                        <div class="author-box d-flex align-items-center">
                                                            <img decoding="async" src="images/zeHnR4NOgj6G.jpeg"/>
                                                            <div class="author-box-content">
                                                                <h5>Rachel Olsem</h5>
                                                                <p>Full Stack Developer</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>

                                        <div class="swiper-button-prev"><i class="iconoir-arrow-left"></i></div>
                                        <div class="swiper-button-next"><i class="iconoir-arrow-right"></i></div>
                                    </div>

                                </div>
                            </section>



                        </div>
                    </div>
                </div>

    )
}

export default Testimonial;